ARG BUILDER_IMAGE=registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.23-openshift-4.19
ARG BASE_IMAGE=registry.redhat.io/rhel9-4-els/rhel-minimal:9.4
ARG GOPATH=/go
ARG REPO_PATH=/go/src/github.com/openshift/kubernetes-sigs-kueue

FROM ${BUILDER_IMAGE} AS builder
ARG TARGETOS
ARG TARGETARCH
ARG TARGETPLATFORM

ENV GOEXPERIMENT=strictfipsruntime \
    GOPATH=${GOPATH} \
    REPO_PATH=${REPO_PATH}

WORKDIR /workspace
COPY . .

RUN CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -tags strictfipsruntime -a -o manager cmd/kueue/main.go

FROM --platform=${TARGETPLATFORM} ${BASE_IMAGE}
ARG REPO_PATH
WORKDIR ${REPO_PATH}
COPY --from=builder /workspace/manager .
RUN mkdir /licenses     
COPY --from=builder /workspace/LICENSE /licenses/.
USER 65532:65532

LABEL com.redhat.component="Kueue"
LABEL name="kueue"
LABEL url="https://github.com/openshift/kubernetes-sigs-kueue"
LABEL vendor="Red Hat, Inc."
LABEL description="Kueue is a set of APIs and controller for job queueing. \
                    It is a job-level manager that decides when a job should \
                    be admitted to start (as in pods can be created) \
                    and when it should stop (as in active pods should be deleted)."
LABEL io.k8s.description="Kueue is a set of APIs and controller for job queueing. \
                    It is a job-level manager that decides when a job should \
                    be admitted to start (as in pods can be created) \
                    and when it should stop (as in active pods should be deleted)."
LABEL summary="Kueue is a set of APIs and controller for job queueing. \
                    It is a job-level manager that decides when a job should \
                    be admitted to start (as in pods can be created) \
                    and when it should stop (as in active pods should be deleted)."
LABEL io.k8s.display-name="Kueue"
LABEL io.openshift.tags="openshift,operand,kueue"

ENTRYPOINT ["/manager"]
